### ISSUE TITLE
Delete backup data and wipe heavy files from commit history

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/asibot-openrave-models#1]
The current size of the working directory (including `.git/`) reaches 222 MB on develop, while [teo-openrave-models](https://github.com/roboticslab-uc3m/teo-openrave-models) weighs "just" 16 MB. There must be some backup data stored at the current HEAD that has to be deleted from the commit history as well. Similar steps have been taken at:

* roboticslab-uc3m/kinematics-dynamics#84
* roboticslab-uc3m/vision#64

**Comment by jgvictores** [comment]
From what I'm seeing there's no Teo here. I'll comment on what I recall of each big file:

Filename     |             Git id             | Comment
---------------|-----------------------------|--------------
ETX0051H.JPG            | f7c634b1 (6.3 MB) | Maybe the wheelchair texture?
cman0007.tif            | ab64f96f (3.0 MB)  | Man on wheelchair texture
cocina.iv               | e69f173a (1.2 MB)  | Kitchen environment
docking.iv              | 8f086087 (1.2 MB)  | Asibot Docking Station
ensam01sn.iv            | c53177a7 (3.5 MB)  | Asibot Part 1
ensam02sn.iv            | f2027f28 (3.7 MB)  | Asibot Part 2
ensam03sn.iv            | ca93b72e (5.9 MB)  | Asibot Part 3
ensam04sn.iv            | 4cce3ac4 (5.8 MB)  | Asibot Part 4
lata.iv                 | ed6b4c3f (12.4 MB) | Coke Can
machosn.iv              | b02a23c3 (1.1 MB)  | Asibot Part 5
wheelchair.iv           | 7e25bc85 (6.1 MB) |  Wheelchair
wheelchairElder.wrl     | 504cd794 (11.9 MB) | Man on wheelchair
wheelchairRheadless.wrl | 3ecd182f (30.0 MB) | Man on wheelchair without head

Where each is used:
- Kitchen environment: used by default.
- Man on wheelchair: not sure if in kitchen environment, but that was the intention. It is used in the asibotTasks app for planning (see [here](https://youtu.be/AYiqmof_IHQ?t=59s)).
- Man on wheelchair without head: to be used with `wheelchairRhead`, we chopped it as two links with a joint in between moved by a physical IMU integrated in AR glasses, and put a simulated camera in the head. Resulting paper was: [Diseño Preliminar de Interfaces de Realidad Aumentada para el Robot Asistencial ASIBOT](https://www.researchgate.net/publication/269632047_Diseno_Preliminar_de_Interfaces_de_Realidad_Aumentada_para_el_Robot_Asistencial_ASIBOT).

Final recommendations:
- For the repo's sake, maybe we could remove the chopped man which is not currently used and was not properly generated, and maybe regenerate one day if ever required again. @PeterBowman What would your opinion be on this?
- What we did in Teo was select heavy models and generate light-weight versions of them. Some were generated from original CAD sources, others were meshes processed in Blender or similar. If we really want to downsize ASIBOT, *please take in mind that this is very time consuming (CAD programs are not really good at preserving absolute positions after processing)*, so let's keep that for the case where run-time memory consumption is really an issue.

**Comment by PeterBowman** [comment]
Agreed on removing unused models or those that are easy to replace/regenerate (please proceed here as you deem more convenient). I was expecting that some of these bigger files were actual backup, which does not seem to be the case as you stated above. Let's see if the removal of the headless man, in case we go on with this, contributes to dropping the overall size of the repo. Otherwise, I'd close this issue as invalid and propose another one with regards to the last point in your comment: investigate a means of downsizing models without loss of precision.

**Comment by jgvictores** [comment]
Ok, I'll go through [openrave/models](https://github.com/roboticslab-uc3m/asibot-openrave-models/tree/359d7dde0856713bb0fd5c715f468047df476756/openrave/models) and see which can be removed (seems reasonable to remove poorly sliced man :slightly_smiling_face:).

**Comment by jgvictores** [comment]
Deleted File Name              |    Git id             
------------------------|---------------------
LAKE3.JPG               | 87e3f2a7 (129.1 KB)
wheelchairRhead.wrl     | e661a183 (157.8 KB)
wheelchairRheadless.wrl | 3ecd182f (30.0 MB)

Result: `99,0 MB` -> `67,3 MB`

PS: Temporarily unprotected `master`. Now protected again.

**Comment by jgvictores** [comment]
In summary:
- Files were deleted at 8386d539d4080a86f9f66b88601eb403199930ea which is now empty because https://rtyley.github.io/bfg-repo-cleaner/ was then used.
- A final [openrave/models/README.md](https://github.com/roboticslab-uc3m/asibot-openrave-models/blob/21a4d9916f5fdc119cb7f1d6d1a5f81c7440737d/openrave/models/README.md) was added at 21a4d9916f5fdc119cb7f1d6d1a5f81c7440737d.

**Comment by jgvictores** [comment]
@PeterBowman Two final comments and I'm closing this issue:
- Removing large unused files has been performed.
- If you want to put an an issue  of regarding downsizing models: It's fairly easy to downsize models and still get okay renders and collision models. Instead, I'd stress on not loosing coordinate systems. Most CAD programs really mess origins up, forcing developers to have to do ugly things like manually adjust coordinates (X,Y,Z, and even 3D orientation) in the [OpenRAVE XML](http://openrave.programmingvision.com/wiki/index.php/Format:XML) (or any other simulator's equivalent).
